templatetest.root."" = ["buildGradle", "text"]
templatetest.root."bob" = ["bob.txt", "bob2.txt"]
templatetest.source."" = ["main_java.pg", "main_java.pg"]

#[templatetest.root]
#    "" = ["buildGradle", "text"]
#    "bob" = ["bob.txt", "bob2.txt"]
#[templatetest.source]
#    "" = ["main_java.pg", "main_kt"]
