name = "gdx"

gdxVersion = '1.1.0'

dependencies = [
    "api:com.badlogicgames.gdx:gdx:1.1.0"
]

project = [
    "api:com.badlogicgames.gdx:gdx:1.1.0"
]

lwjgl3 = [
    "implementation:com.badlogicgames.gdx:gdx-backend-lwjgl3:1.1.0",
	"implementation:com.badlogicgames.gdx:gdx-platform:1.1.0:natives-desktop"
]